// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// treat_img
NumericVector treat_img(const NumericVector& in_vec, int height, int width, int channels, bool verbose);
RcppExport SEXP _seamcarvdijkstra_treat_img(SEXP in_vecSEXP, SEXP heightSEXP, SEXP widthSEXP, SEXP channelsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type in_vec(in_vecSEXP);
    Rcpp::traits::input_parameter< int >::type height(heightSEXP);
    Rcpp::traits::input_parameter< int >::type width(widthSEXP);
    Rcpp::traits::input_parameter< int >::type channels(channelsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(treat_img(in_vec, height, width, channels, verbose));
    return rcpp_result_gen;
END_RCPP
}
// time_treat
double time_treat(const NumericVector& in_vec, int height, int width, int channels, bool verbose);
RcppExport SEXP _seamcarvdijkstra_time_treat(SEXP in_vecSEXP, SEXP heightSEXP, SEXP widthSEXP, SEXP channelsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type in_vec(in_vecSEXP);
    Rcpp::traits::input_parameter< int >::type height(heightSEXP);
    Rcpp::traits::input_parameter< int >::type width(widthSEXP);
    Rcpp::traits::input_parameter< int >::type channels(channelsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(time_treat(in_vec, height, width, channels, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_seamcarvdijkstra_treat_img", (DL_FUNC) &_seamcarvdijkstra_treat_img, 5},
    {"_seamcarvdijkstra_time_treat", (DL_FUNC) &_seamcarvdijkstra_time_treat, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_seamcarvdijkstra(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
