# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Apply Seam-Carving image reduction to an image
#' @description Seam-Carving with Dijkstra path-finding
#' @description This is the C++ implementation, you can use the R convenience function treat( img, verbose )
#'
#' @param in_vec Rcpp::NumericVector input vector, with dimension c(height * width * channels)
#' @param height int number of rows in the image
#' @param width int number of columns in the image
#' @param channels int number of byte per pixel in the image
#' @param verbose bool set to true to print progress to console
#' @export
treat_img <- function(in_vec, height, width, channels, verbose) {
    .Call(`_seamcarvdijkstra_treat_img`, in_vec, height, width, channels, verbose)
}

#' Time the Seam-Carving image reduction of an image
#' @description Seam-Carving with Dijkstra path-finding
#' @description This is the C++ implementation, you can use the R convenience function timedrun( img, verbose )
#'
#' @param in_vec Rcpp::NumericVector input vector, with dimension c(height * width * channels)
#' @param height int number of rows in the image
#' @param width int number of columns in the image
#' @param channels int number of byte per pixel in the image
#' @param verbose bool set to true to print progress to console
#' @export
time_treat <- function(in_vec, height, width, channels, verbose) {
    .Call(`_seamcarvdijkstra_time_treat`, in_vec, height, width, channels, verbose)
}

